### ISSUE TITLE
Multi project builds don't seem to put Clojure source of dep on classpath

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#109]
## Expected Behavior

Successful checkClojure tasks when one subproject depends on a namespace in another (and using a `implementation project(':subB')` dep).

## Current Behavior

```
[jovial|updates ≡]$ ./gradlew check

> Configure project :jovial-engine-clojure.test
Reckoned version: 0.3.0-beta.0.9+20181201T200620Z

> Task :jovial-engine-clojure.test:checkClojure FAILED
Exception in thread "main" ERROR java.io.FileNotFoundException: Could not locate org/ajoberstar/jovial/lang/clojure__init.class or org/ajoberstar/jovial/lang/clojure.clj on classpath., compiling:(org/ajoberstar/jovial/engine/clojure_test.clj:1:1)
java.io.FileNotFoundException: Could not locate org/ajoberstar/jovial/lang/clojure__init.class or org/ajoberstar/jovial/lang/clojure.clj on classpath., compiling:(org/ajoberstar/jovial/engine/clojure_test.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at gradle_clojure.tools.clojure_loader$_main$fn__37.invoke(clojure_loader.clj:30)
        at gradle_clojure.tools.clojure_loader$_main.invokeStatic(clojure_loader.clj:23)
        at gradle_clojure.tools.clojure_loader$_main.doInvoke(clojure_loader.clj:19)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.main$main_opt.invokeStatic(main.clj:314)
        at clojure.main$main_opt.invoke(main.clj:310)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate org/ajoberstar/jovial/lang/clojure__init.class or org/ajoberstar/jovial/lang/clojure.clj on classpath.
        at clojure.lang.RT.load(RT.java:456)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at org.ajoberstar.jovial.engine.clojure_test$eval51$loading__5569__auto____52.invoke(clojure_test.clj:1)
        at org.ajoberstar.jovial.engine.clojure_test$eval51.invokeStatic(clojure_test.clj:1)
        at org.ajoberstar.jovial.engine.clojure_test$eval51.invoke(clojure_test.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 25 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jovial-engine-clojure.test:checkClojure'.
> Process 'command 'C:\Program Files\Zulu\zulu-11\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
10 actionable tasks: 5 executed, 5 up-to-date
```

## Context

Makes it impractical to develop two Clojure libraries in a multi-project build. Would need to AOT compile the classes, which isn't what you should need to do.

## Steps to reproduce

1. Create a new build with two subprojects
1. Both projects should be Clojure libraries (that produce source-only JARs)
1. One project should depend on a namespace from the other
1. Run the check tasks and verify that the project cannot see namespaces from the other project

## Environment

- **Build scan URL:**
- **gradle-clojure version:** 0.4.0
- **Gradle version:** 5.0
- **Java version:** 11.0.1
- **OS version:** Windows 10

**Comment by ajoberstar** [comment]
Fairly confident this is fixed by ba42d4dabe5e714bc7d87cc048d577538756e595.
