### ISSUE TITLE
:gen-class casing gets mangled

### ISSUE THREAD

**Issue by mcandre** [gradle-clojure/gradle-clojure#113]
## Expected Behavior

`(ns us.yellosoft.args.Args (:gen-class))` passes `gradle build`, as it does under the old de.kotka.clojuresque.clojure plugin.

## Current Behavior

Gradle reports a compile error during compilation:

```console
$ gradle build
> Task :compileClojure FAILED
ERROR java.lang.Exception: namespace 'us.yellosoft.args.args' not found after loading '/us/yellosoft/args/args', compiling:(NO_SOURCE_PATH:0:0)
Exception in thread "main" java.lang.Exception: namespace 'us.yellosoft.args.args' not found after loading '/us/yellosoft/args/args', compiling:(NO_SOURCE_PATH:0:0)
        at clojure.core$throw_if.doInvoke(core.clj:5630)
        at clojure.lang.RestFn.invoke(RestFn.java:464)
        at clojure.core$load_one.invoke(core.clj:5672)
        at clojure.core$compile$fn__5453.invoke(core.clj:5877)
        at clojure.core$compile.invoke(core.clj:5876)
        at gradle_clojure.tools.clojure_compiler$_main.doInvoke(clojure_compiler.clj:16)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.main$main_opt.invoke(main.clj:316)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: namespace 'us.yellosoft.args.args' not found after loading '/us/yellosoft/args/args'
        ... 16 more

FAILURE: Build failed with an exception.
```

As a workaround, I am converting my Clojure namespaces to all lowercase. So it seems that the gradle-closure plugin is somehow mangling the namespace casing, compared to how the old plugin worked. As a consequence of using explicitly lowercase class name workarounds, SpotBugs reports warnings about lowercase classnames :/

In order to work around *that* issue, I am temporarily disabling that rule for my Clojure projects in a spotbugs `excludes.xml` file:

```xml
<Match>
    <Bug pattern="NM_CLASS_NAMING_CONVENTION" />
</Match>
```

## Environment

```console
$ gradle --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by ajoberstar** [comment]
I'll be responding to #115 about SpotBugs in general, but considering these all won't fix as there's no clear problem in gradle-clojure.
