### ISSUE TITLE
Exiting REPL in Atom proto-repl throws exception

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#49]
## Expected Behavior

Exiting a REPL should not throw an exception.

## Current Behavior

A `MessageIOException` is being thrown saying it can't write to the socket.

## Environment

| **Component**  | **Version** |
|----------------|-------------|
| gradle-clojure | 0.3.0 |
| Gradle         | 4.3 |
| Java           | 9.0.1 |
| OS             | Windows 10 |

## Logs

**Switches used:** none

```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:59696'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:134)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:325)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:473)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:272)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:260)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:254)
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:132)
	... 7 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clojureRepl'.
> There was a failure while executing work items
   > java.util.concurrent.ExecutionException: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing gradle_clojure.plugin.internal.ClojureWorker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 18s
```

**Comment by ajoberstar** [comment]
This is a proto-repl issue, rather than ours. I've got a fix in the fork.
