### ISSUE TITLE
Tests can hang on Java 9 and 10

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#62]
## Expected Behavior

`./gradlew test` should end after tests have been executed.

## Current Behavior

Tests are failing due to an `IllegalAccessError` and then it hangs and never completes. I'm not sure if this is bad error handling within gradle-clojure or just a Java 9 or 10 issue.

[Java 9](https://circleci.com/gh/ajoberstar/ike.cljj/4)
[Java 10](https://circleci.com/gh/ajoberstar/ike.cljj/3)

## Environment

| **Component**  | **Version** |
|----------------|-------------|
| gradle-clojure | 0.3.1 |
| Gradle         | 4.6 |
| Java           | 9 and 10 |
| OS             | Windows and Linux |

## Logs

**Switches used:** used the full exceptionFormat in the testLogging config.

```
ike.cljj.function-test > supplier FAILED
    java.lang.AssertionError: ERROR in  (supplier) (Reflection.java:360)
    expected:  (= supplied (.get f))
      actual:  #error {
     :cause class clojure.lang.Reflector cannot access class com.sun.proxy.jdk.proxy1.$Proxy9 (in module jdk.proxy1) because module jdk.proxy1 does not export com.sun.proxy.jdk.proxy1 to unnamed module @a97c972
     :via
     [{:type java.lang.IllegalAccessException
       :message class clojure.lang.Reflector cannot access class com.sun.proxy.jdk.proxy1.$Proxy9 (in module jdk.proxy1) because module jdk.proxy1 does not export com.sun.proxy.jdk.proxy1 to unnamed module @a97c972
       :at [jdk.internal.reflect.Reflection newIllegalAccessException Reflection.java 360]}]
     :trace
     [[jdk.internal.reflect.Reflection newIllegalAccessException Reflection.java 360]
      [java.lang.reflect.AccessibleObject checkAccess AccessibleObject.java 589]
      [java.lang.reflect.Method invoke Method.java 556]
      [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
      [clojure.lang.Reflector invokeNoArgInstanceMember Reflector.java 313]
      [ike.cljj.function_test$fn__826 invokeStatic function_test.clj 8]
      [ike.cljj.function_test$fn__826 invoke function_test.clj 6]
      [gradle_clojure.tools.clojure_test_junit4$test_var invokeStatic clojure_test_junit4.clj 83]
      [gradle_clojure.tools.clojure_test_junit4$test_var invoke clojure_test_junit4.clj 80]
      [gradle_clojure.tools.clojure_test_junit4$run_test$fn__272$fn__273 invoke clojure_test_junit4.clj 93]
      [clojure.test$default_fixture invokeStatic test.clj 686]
      [clojure.test$default_fixture invoke test.clj 682]
      [gradle_clojure.tools.clojure_test_junit4$run_test$fn__272 invoke clojure_test_junit4.clj 91]
      [gradle_clojure.tools.clojure_test_junit4$run_test invokeStatic clojure_test_junit4.clj 90]
      [gradle_clojure.tools.clojure_test_junit4$run_test invoke clojure_test_junit4.clj 87]
      [gradle_clojure.tools.clojure_test_junit4$run_suite$fn__277$fn__278 invoke clojure_test_junit4.clj 109]
      [clojure.test$default_fixture invokeStatic test.clj 686]
      [clojure.test$default_fixture invoke test.clj 682]
      [gradle_clojure.tools.clojure_test_junit4$run_suite$fn__277 invoke clojure_test_junit4.clj 106]
      [gradle_clojure.tools.clojure_test_junit4$run_suite invokeStatic clojure_test_junit4.clj 105]
      [gradle_clojure.tools.clojure_test_junit4$run_suite invoke clojure_test_junit4.clj 98]
      [gradle_clojure.tools.clojure_test_junit4$_run invokeStatic clojure_test_junit4.clj 132]
      [gradle_clojure.tools.clojure_test_junit4$_run invoke clojure_test_junit4.clj 131]
      [gradle_clojure.tools.ClojureTestRunner run nil -1]
      [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor runTestClass JUnitTestClassExecutor.java 116]
      [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor execute JUnitTestClassExecutor.java 59]
      [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor execute JUnitTestClassExecutor.java 39]
      [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor processTestClass AbstractJUnitTestClassProcessor.java 66]
      [org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor processTestClass SuiteTestClassProcessor.java 51]
      [jdk.internal.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
      [jdk.internal.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
      [jdk.internal.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
      [java.lang.reflect.Method invoke Method.java 564]
      [org.gradle.internal.dispatch.ReflectionDispatch dispatch ReflectionDispatch.java 35]
      [org.gradle.internal.dispatch.ReflectionDispatch dispatch ReflectionDispatch.java 24]
      [org.gradle.internal.dispatch.ContextClassLoaderDispatch dispatch ContextClassLoaderDispatch.java 32]
      [org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler invoke ProxyDispatchAdapter.java 93]
```

**Comment by ajoberstar** [comment]
Here's another of a similar, if not the same, issue:

```
> Task :compileTestClojure FAILED
ERROR java.lang.IllegalAccessException: no such method: clojure.lang.RT.seq(Object)ISeq/invokeStatic, compiling:(function.clj:24:3)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestClojure'.
> A failure occurred while executing gradle_clojure.plugin.internal.ClojureWorker
   > java.lang.IllegalAccessException: no such method: clojure.lang.RT.seq(Object)ISeq/invokeStatic, compiling:(function.clj:24:3)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileTestClojure'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing gradle_clojure.plugin.internal.ClojureWorker
        at org.gradle.workers.internal.DefaultWorkerExecutor$2.waitForCompletion(DefaultWorkerExecutor.java:143)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:99)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.access$000(DefaultAsyncWorkTracker.java:34)
        at org.gradle.internal.work.DefaultAsyncWorkTracker$2.run(DefaultAsyncWorkTracker.java:83)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:196)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutProjectLock(DefaultWorkerLeaseService.java:145)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:79)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:132)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 31 more
Caused by: java.lang.IllegalAccessException: no such method: clojure.lang.RT.seq(Object)ISeq/invokeStatic, compiling:(function.clj:24:3)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
        at clojure.lang.Compiler.compile1(Compiler.java:7609)
        at clojure.lang.Compiler.compile(Compiler.java:7676)
        at clojure.lang.RT.compile(RT.java:413)
        at clojure.lang.RT.load(RT.java:458)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at ike.cljj.stream$loading__6434__auto____329.invoke(stream.clj:1)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
        at clojure.lang.Compiler.compile1(Compiler.java:7609)
        at clojure.lang.Compiler.compile1(Compiler.java:7599)
        at clojure.lang.Compiler.compile(Compiler.java:7676)
        at clojure.lang.RT.compile(RT.java:413)
        at clojure.lang.RT.load(RT.java:458)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at ike.cljj.file$loading__6434__auto____327.invoke(file.clj:1)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
        at clojure.lang.Compiler.compile1(Compiler.java:7609)
        at clojure.lang.Compiler.compile1(Compiler.java:7599)
        at clojure.lang.Compiler.compile(Compiler.java:7676)
        at clojure.lang.RT.compile(RT.java:413)
        at clojure.lang.RT.load(RT.java:458)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at ike.cljj.file_test$loading__6434__auto____325.invoke(file_test.clj:1)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
        at clojure.lang.Compiler.compile1(Compiler.java:7609)
        at clojure.lang.Compiler.compile1(Compiler.java:7599)
        at clojure.lang.Compiler.compile(Compiler.java:7676)
        at clojure.lang.RT.compile(RT.java:413)
        at clojure.lang.RT.load(RT.java:458)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$compile$fn__6553.invoke(core.clj:6056)
        at clojure.core$compile.invokeStatic(core.clj:6056)
        at clojure.core$compile.invoke(core.clj:6048)
        at gradle_clojure.tools.clojure_compiler$compiler$fn__180.invoke(clojure_compiler.clj:37)
        at gradle_clojure.tools.clojure_compiler$compiler.invokeStatic(clojure_compiler.clj:28)
        at gradle_clojure.tools.clojure_compiler$compiler.invoke(clojure_compiler.clj:26)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.core$apply.invoke(core.clj:652)
        at clojure.lang.Var.invoke(Var.java:385)
        at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:124)
        at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:117)
        at gradle_clojure.plugin.internal.ClojureWorker.run(ClojureWorker.java:56)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:36)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:100)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        ... 3 more
Caused by: java.lang.IllegalAccessException: no such method: clojure.lang.RT.seq(Object)ISeq/invokeStatic
        at ike.cljj.internal.invoke$static_handle.invokeStatic(invoke.clj:39)
        at ike.cljj.internal.invoke$static_handle.invoke(invoke.clj:33)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
        ... 128 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "clojure.lang.RT.seq(Ljava/lang/Object;)Lclojure/lang/ISeq;" the class loader (instance of <bootloader>) of the current class, java/lang/Object, and the class loader (instance of gradle_clojure/plugin/internal/ClojureWorkerClassLoader) for the method's defining class, clojure/lang/RT, have different Class objects for the type clojure/lang/ISeq used in the signature
        ... 133 more


* Get more help at https://help.gradle.org

BUILD FAILED in 3s
3 actionable tasks: 3 executed
```

**Comment by ajoberstar** [comment]
Both of these issues turned out to be in ike.cljj. The test hanging is concerning, but since we're going through Gradle's normal `Test` task, I'm not sure if it would be due to anything in this plugin.
